[build]
  functions = "serverless/"
  command = "npm run dev"  # Your preferred build command

[build.environment]
  NODE_VERSION = "18.16.0"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/pokemon"
  to = "/.netlify/functions/pokemon"

[[redirects]]
  from = "/pokemon/:id"
  to = "/.netlify/functions/pokemon/:id"

[[redirects]]
  from = "/pokemon/:id/:info"
  to = "/.netlify/functions/pokemon/:id/:info"
